name: 'PNPM & Turbo Cache'
description: 'PNPM & Turbo Cache'
runs:
  using: 'composite'
  steps:
    - name: Cache turbo build setup
      uses: actions/cache@v3
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - uses: pnpm/action-setup@a0853c24544627f65ddf259abe73b1d18a591444
      name: Install pnpm
      with:
        run_install: false

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version-file: './package.json'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install
      shell: bash
